# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/
title: Kevin Adu
author: Kevin Adu
language: en
timezone:
since: 2016 # The start year showing in your copyright section.

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://blog.kevinadu.com
new_post_name: :lang/:title.md
permalink: :lang/:title/
permalink_defaults:
  lang: en


# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  tab_replace:

# Category & Tag
default_category: Life
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: DD-MM-YYYY
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 6
pagination_dir: page

# Extensions
## Plugins: https://github.com/hexojs/hexo/wiki/Plugins
## Themes: https://github.com/hexojs/hexo/wiki/Themes
theme: icarus

feed:
  type: rss2
  path: rss2.xml
  limit: 20
  hub:

# DuoShuo
# duoshuo_shortname: hexo-theme-icarus

# Swiftype
# swiftype_install_key: XXX_XXXXXXXXXXXXXXXX

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: s3
  bucket: blog.kevinadu.com
  region: ap-northeast-1